### ISSUE TITLE
reports installed, but lots of error output first

### ISSUE THREAD

**Issue by wwalker** [taylor/kiex#10]
$ kiex install 0.12.5
grep: /etc/lsb-release: No such file or directory
Unknown Linux distribution
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Note: checking out 'v0.12.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at b07fbcf... Release v0.12.5
From https://github.com/elixir-lang/elixir
- tag               v0.12.5    -> FETCH_HEAD
  Already up-to-date.
  cd lib/elixir && ../../rebar clean
  Uncaught error in rebar_core: {'EXIT',
                             {undef,
                              [{crypto,start,[],[]},
                               {rebar,run_aux,2,
                                [{file,"src/rebar.erl"},{line,163}]},
                               {rebar,main,1,
                                [{file,"src/rebar.erl"},{line,58}]},
                               {escript,run,2,
                                [{file,"escript.erl"},{line,747}]},
                               {escript,start,1,
                                [{file,"escript.erl"},{line,277}]},
                               {init,start_it,1,[]},
                               {init,start_em,1,[]}]}}
  make: **\* [clean] Error 1
  Uncaught error in rebar_core: {'EXIT',
                             {undef,
                              [{crypto,start,[],[]},
                               {rebar,run_aux,2,
                                [{file,"src/rebar.erl"},{line,163}]},
                               {rebar,main,1,
                                [{file,"src/rebar.erl"},{line,58}]},
                               {escript,run,2,
                                [{file,"escript.erl"},{line,747}]},
                               {escript,start,1,
                                [{file,"escript.erl"},{line,277}]},
                               {init,start_it,1,[]},
                               {init,start_em,1,[]}]}}
  make: **\* [erlang] Error 1
  Installed Elixir version 0.12.5
  Load with:
         kiex use 0.12.5 
  or load the elixir environment file with: 
  source $HOME/.kiex/elixirs/elixir-0.12.5.env

**Comment by zaidshaikh112** [comment]
i there any think to resolve on ubuntu 16.4 and am using Erlang/OTP 18 [erts-7.1] [source] [64-bit] [async-threads:10] [kernel-poll:false]
