### ISSUE TITLE
Stable is not a valid release target

### ISSUE THREAD

**Issue by eproxus** [taylor/kiex#29]
```
$ kiex install stable
Unknown Elixir 'stable' ☹
Try
	kiex list known -- known releases
	kiex list branches -- current branches
```

**Comment by taylor** [comment]
There is no longer a 'stable' tag, branch, or release.

The only place I see a version and stable mentioned are when visiting the "stable" docs and you see the version.  Eg. http://elixir-lang.org/docs/stable/elixir/Kernel.html showed 1.2.5 when I typed this.

Until I find a way to have stable be in sync with what the Elixir team considers stable I have updated the README to remove stable from the examples.
