### ISSUE TITLE
sort: unrecognized option `--version-sort'

### ISSUE THREAD

**Issue by kipcole9** [taylor/kiex#49]
After installation this morning (my first install) the following error occurs with `kiex list known` and `kiex install .....`.  Mac OSX El Cap, all updates installed.  Checking `sort --help` confirms that options isn't available, I guess its a Gnu sort option.

```
Kips-iMac:traphos kip$ kiex list known
Getting the available releases from https://github.com/elixir-lang/elixir/releases

sort: unrecognized option `--version-sort'
```

**Comment by taylor** [comment]
@kipcole9 Thanks for reporting the problem. This update should fix the issue.  Let me know if you have any more trouble.
