### ISSUE TITLE
Error when installing using erlang installed with kerl in  CentosOS

### ISSUE THREAD

**Issue by tinat** [taylor/kiex#7]
This is the error I got when I ran "kiex install 0.12.4" (using bash shell)

HEAD is now at 543dfde... Release v0.12.4
cd lib/elixir && ../../rebar clean
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,163}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,747}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: **\* [clean] Error 1
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,2,
                                  [{file,"src/rebar.erl"},{line,163}]},
                                 {rebar,main,1,
                                  [{file,"src/rebar.erl"},{line,58}]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,747}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: **\* [erlang] Error 1

Conditions:  CentosOS 6,  erlang in $HOME/packages/erlang_r16b03, activated with command ". $HOME/packages/erlang_r16b03/activate"  

I have erlang installed in $HOME/packages/erlang with the regular "configure; make; make install" commands and if I removed all the environment settings from the kerl activate command and just set my PATH to include $HOME/packages/erlang  then "kiex install 0.12.4" works fine.

One difference between the kerl installed erlang directory and the "configure; make;make-install directory" is the bin directory contains symbolic links to the lib directory and what is in the kerl package lib directory is actually found in lib/erlang 

What confuses me is that "kiex install 0.12.4"  works fine on my Mac OSX machine with both the kerl activated versions of erlang.and the "configure; make; make install" version. 

Thanks,
Tina

**Comment by jmarkbrooks** [comment]
Thanks for this.  Somebody needs to make a note of it at the kerl site, because I have Mint 17.1 and the error confused me.  The CFLAGS addition to my .kerlrc fixed the problem.

**Comment by MerkerXu** [comment]
I met the same problem, and I solved it according to:  http://stackoverflow.com/questions/6618233/openssl-error-building-erlang-otp-from-source

**Comment by yaohuaxin** [comment]
For PPC64LE:
./configure --prefix=/home/huaxin/huaxin/toolsInstalled/ --build=ppc64le CFLAGS="-D_GNU_SOURCE -DOPENSSL_NO_EC=1"
then make 
then make install

**Comment by alexshavelev** [comment]
adding KERL_CONFIGURE_OPTIONS="--with-ssl=/usr/lib/ssl" and rebuild also works

**Comment by wingleungchoi** [comment]
There is related issue opened in Kerl and the solution is there
add --with-ssl=/usr/local/opt/openssl to KERL_CONFIGURE_OPTIONS in ~/.kerlrc
```
export KERL_CONFIGURE_OPTIONS="--with-ssl=/usr/local/opt/openssl"
```
https://github.com/kerl/kerl/issues/103

**Comment by mrallen1** [comment]
For the record the problem is that Red Hat has refused to ship elliptic curve crypto for OpenSSL for well over 10 years because Red Hat believes ECC is covered by patents.  There is a tracking ticket in kerl: https://github.com/kerl/kerl/issues/212
