### ISSUE TITLE
-bash: kiex: command not found

### ISSUE THREAD

**Issue by English3000** [taylor/kiex#83]
```
~$ \curl -sSL https://raw.githubusercontent.com/taylor/kiex/master/install | bash -s
Updating the kiex installation in /Users/amarkskatz/.kiex
    Kiex sourcing line found in: /Users/amarkskatz/.bashrc
kiex installed in /Users/amarkskatz/.kiex is now updated ☺
~$ kiex list
-bash: kiex: command not found
```

**Comment by taylor** [comment]
Please show the kiex line from the .bashrc

**Comment by English3000** [comment]
`test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"`

**Comment by taylor** [comment]
What happens when you run that manually then type kiex?

**Comment by taylor** [comment]
If it's not working with a new terminal it may be that your .bashrc is not being loaded for new sessions.  You can enable that for some terminal emulators or load it from .bash_profile.
