### ISSUE TITLE
No versions of elixir found

### ISSUE THREAD

**Issue by aturkewi** [taylor/kiex#85]
No versions of elixir showing up. I had previously installed versions on my local.

```bash
// ♥ kiex list known
Getting the available releases from https://github.com/elixir-lang/elixir/releases

Known Elixir releases:

```
I saw this issue https://github.com/taylor/kiex/issues/52 and tried opening a new shell. I still could not list any versions. 

I tried imploding and re-installing kiex with curl and I'm still not seeing an versions of elixir showing up. 

I have the following loading up in my bash profile:
```bash
# Kiex - Elixir Version Manager
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"
```

**Comment by janispauls** [comment]
+1

**Comment by kanes115** [comment]
+1

**Comment by kanes115** [comment]
In my case this was due to the github api not working for some time. It would be still nice if there was a message that describes what kind of issue kiex had while fetching releases.

**Comment by taylor** [comment]
It is likely that it was a GitHub API error as it is working again.

![image](https://user-images.githubusercontent.com/26697/129226310-6a820efe-6563-421c-a2b5-03e6bcdb8842.png)

Good idea on the message describing an error when fetching a release name. If this comes up again we can look at adding that. Feel free to contribute something ahead of time though (testing with a fake failure etc).
