### ISSUE TITLE
kiex install - 'make' command not found

### ISSUE THREAD

**Issue by wagncarv** [taylor/kiex#91]
Downloading elixir version 1.11.3
Installing elixir version 1.11.3
Switched to branch 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 44 (delta 36), reused 32 (delta 25), pack-reused 0
Unpacking objects: 100% (44/44), 5.14 KiB | 31.00 KiB/s, done.
From https://github.com/elixir-lang/elixir
   c34fa0ca5..7795cfc48  master     -> origin/master
warning: refname 'v1.11.3' is ambiguous.
fatal: A branch named 'v1.11.3' already exists.
warning: refname 'v1.11.3' is ambiguous.
Switched to branch 'v1.11.3'
From https://github.com/elixir-lang/elixir
 * tag                   v1.11.3    -> FETCH_HEAD
Already up to date.
/home/wagnercarvalho/.kiex/bin/kiex: linha 617: make: comando não encontrado
/home/wagnercarvalho/.kiex/bin/kiex: linha 620: make: comando não encontrado
Problem with Elixir build.  Aborting!

**Comment by wagncarv** [comment]
Issue solved.
I just installed 'make' command and it worked.
Thanks

**Comment by taylor** [comment]
Yes, make is listed as a prereq in the [install section](https://github.com/taylor/kiex#install). If there are any other prereqs we can update the README. ATM we have the following:

> Prerequisites: bash, curl, erlang, git, make, openssl
